FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["EWebDataApi/EWebDataApi.csproj", "EWebDataApi/"]
RUN dotnet restore "EWebDataApi/EWebDataApi.csproj"
COPY . .
WORKDIR "/src/EWebDataApi"
RUN dotnet build "EWebDataApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EWebDataApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EWebDataApi.dll"]
